import { StyleSheet, Dimensions } from 'react-native';
import { Linking } from 'expo-linking';
import { COLORS, SPACING } from './index.constants';

const { width, height } = Dimensions.get('window');
export const isSmallScreen = width < 768;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.cream,
  },
  loadingContainer: {
    flex: 1,
    backgroundColor: COLORS.cream,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingContent: {
    alignItems: 'center',
    gap: SPACING.lg,
  },
  loadingText: {
    fontSize: 18,
    color: COLORS.charcoal,
    fontWeight: '600',
  },
  scrollView: {
    flex: 1,
  },

  // Floating Header
  floatingHeader: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 1000,
    paddingTop: isSmallScreen ? 40 : 45,
    paddingBottom: SPACING.sm,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.cloud,
  },
  headerContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: SPACING.md,
  },
  logoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
    flex: 1,
    justifyContent: 'center',
  },
  logoText: {
    fontSize: 16,
    fontWeight: '800',
    color: COLORS.forest,
    letterSpacing: -0.5,
  },
  loginButton: {
    borderRadius: 20,
    overflow: 'hidden',
    width: 80,
    shadowColor: COLORS.forest,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  loginButtonGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
    paddingHorizontal: 12,
    gap: 4,
  },
  loginButtonText: {
    color: COLORS.white,
    fontSize: 12,
    fontWeight: '700',
  },

  // Hero Section
  heroSection: {
    height: isSmallScreen ? height * 0.7 : height * 0.75,
    position: 'relative',
  },
  heroImageContainer: {
    ...StyleSheet.absoluteFillObject,
  },
  heroImage: {
    width: '100%',
    height: '100%',
  },
  heroGradient: {
    ...StyleSheet.absoluteFillObject,
  },
  heroContent: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    paddingHorizontal: SPACING.lg,
    paddingBottom: isSmallScreen ? 40 : 35,
  },
  welcomeBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    paddingVertical: 6,
    paddingHorizontal: SPACING.md,
    borderRadius: 20,
    marginBottom: SPACING.md,
    maxWidth: '90%',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  welcomeText: {
    color: COLORS.white,
    fontSize: 13,
    fontWeight: '600',
    flexShrink: 1,
  },
  heroTitle: {
    fontSize: isSmallScreen ? 28 : 40,
    fontWeight: '900',
    color: COLORS.white,
    lineHeight: isSmallScreen ? 34 : 48,
    marginBottom: SPACING.md,
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 8,
  },
  heroSubtitle: {
    fontSize: isSmallScreen ? 14 : 15,
    color: 'rgba(255, 255, 255, 0.95)',
    lineHeight: isSmallScreen ? 20 : 22,
    marginBottom: SPACING.lg,
    maxWidth: '95%',
  },
  heroActions: {
    flexDirection: 'column',
    gap: SPACING.md,
    marginBottom: SPACING.md,
  },
  primaryButton: {
    borderRadius: 25,
    overflow: 'hidden',
    shadowColor: COLORS.forest,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  buttonGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.lg,
    gap: SPACING.sm,
  },
  primaryButtonText: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: '700',
  },
  secondaryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: SPACING.sm,
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.lg,
    borderRadius: 25,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  secondaryButtonText: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: '600',
  },
  slideIndicators: {
    flexDirection: 'row',
    gap: SPACING.sm,
    justifyContent: 'center',
  },
  indicator: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: 'rgba(255, 255, 255, 0.4)',
  },
  activeIndicator: {
    backgroundColor: COLORS.white,
    width: 24,
  },

  // Stats Bar
  statsBar: {
    flexDirection: 'row',
    backgroundColor: COLORS.white,
    paddingVertical: SPACING.lg,
    paddingHorizontal: SPACING.md,
    justifyContent: 'space-around',
    borderBottomWidth: 1,
    borderBottomColor: COLORS.cloud,
  },
  statItem: {
    alignItems: 'center',
    gap: SPACING.xs,
    flex: 1,
  },
  statNumber: {
    fontSize: isSmallScreen ? 16 : 18,
    fontWeight: '800',
    color: COLORS.forest,
    textAlign: 'center',
  },
  statLabel: {
    fontSize: 11,
    color: COLORS.stone,
    fontWeight: '500',
    textAlign: 'center',
  },
  statDivider: {
    width: 1,
    backgroundColor: COLORS.cloud,
  },

  // Resources Section
  resourcesSection: {
    paddingVertical: SPACING.xl,
    paddingHorizontal: SPACING.md,
    backgroundColor: COLORS.cream,
  },
  resourcesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    justifyContent: 'space-between',
  },
  resourceCard: {
    flexDirection: 'column',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    borderRadius: 16,
    padding: 16,
    gap: 10,
    borderWidth: 1,
    borderColor: COLORS.cloud,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
    width: '48%' as any,
    minHeight: 140,
  },
  resourceIcon: {
    width: 48,
    height: 48,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  resourceContent: {
    flex: 1,
    gap: 4,
    alignItems: 'center',
  },
  resourceTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: COLORS.charcoal,
    textAlign: 'center',
  },
  resourceDesc: {
    fontSize: 11,
    color: COLORS.stone,
    lineHeight: 15,
    textAlign: 'center',
  },

  // Infographics Section
  infographicsSection: {
    paddingVertical: SPACING.xxl,
    paddingHorizontal: SPACING.md,
    backgroundColor: COLORS.sand,
    position: 'relative',
  },
  sectionHeader: {
    alignItems: 'center',
    marginBottom: SPACING.xl,
    paddingHorizontal: SPACING.sm,
  },
  sectionBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    paddingVertical: 6,
    paddingHorizontal: SPACING.md,
    borderRadius: 20,
    marginBottom: SPACING.md,
    borderWidth: 1,
    borderColor: COLORS.cloud,
  },
  sectionLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: COLORS.forest,
    letterSpacing: 1.5,
  },
  sectionTitle: {
    fontSize: isSmallScreen ? 24 : 32,
    fontWeight: '800',
    color: COLORS.charcoal,
    marginBottom: SPACING.sm,
    textAlign: 'center',
  },
  sectionDescription: {
    fontSize: isSmallScreen ? 14 : 16,
    color: COLORS.stone,
    textAlign: 'center',
    maxWidth: 540,
    lineHeight: 22,
  },

  // Tab Navigation
  tabContainer: {
    flexDirection: 'row',
    backgroundColor: COLORS.white,
    padding: 4,
    borderRadius: 16,
    marginBottom: SPACING.lg,
    borderWidth: 1,
    borderColor: COLORS.cloud,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  tabButton: {
    flex: 1,
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.xs,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    borderRadius: 12,
  },
  activeTabButton: {
    backgroundColor: COLORS.sage,
  },
  tabText: {
    fontSize: isSmallScreen ? 10 : 11,
    fontWeight: '600',
    color: COLORS.stone,
  },
  activeTabText: {
    color: COLORS.white,
    fontWeight: '700',
  },

  // Content Area
  contentArea: {
    minHeight: 450,
  },
  tabContent: {
    flex: 1,
  },

  // Facts Tab
  factsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: SPACING.md,
    justifyContent: 'center',
  },
  factCard: {
    width: isSmallScreen ? '47%' : '31%',
    minWidth: isSmallScreen ? 150 : 140,
    maxWidth: 180,
    borderRadius: 18,
    overflow: 'visible',
  },
  factCardInner: {
    padding: SPACING.lg,
    minHeight: 190,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: COLORS.cloud,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 3,
  },
  factIconContainer: {
    width: 50,
    height: 50,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: SPACING.md,
  },
  factStats: {
    marginBottom: SPACING.md,
  },
  factStat: {
    fontSize: 22,
    fontWeight: '800',
    marginBottom: SPACING.xs,
  },
  factSubtext: {
    fontSize: 10,
    fontWeight: '600',
  },
  factCardTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: COLORS.charcoal,
    marginBottom: SPACING.sm,
  },
  factCardDescription: {
    fontSize: 12,
    color: COLORS.stone,
    lineHeight: 18,
  },

  // Anatomy Tab
  anatomyContainer: {
    flex: 1,
  },
  diagramContainer: {
    alignItems: 'center',
    marginBottom: SPACING.lg,
    padding: SPACING.lg,
    backgroundColor: COLORS.white,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: COLORS.cloud,
  },
  diagramLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: COLORS.stone,
    marginTop: SPACING.md,
  },
  partsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: SPACING.md,
    justifyContent: 'center',
  },
  partCard: {
    width: isSmallScreen ? '47%' : '31%',
    minWidth: isSmallScreen ? 150 : 140,
    maxWidth: 180,
    backgroundColor: COLORS.white,
    padding: SPACING.lg,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: COLORS.cloud,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  partIconContainer: {
    width: 50,
    height: 50,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: SPACING.md,
  },
  partName: {
    fontSize: 14,
    fontWeight: '700',
    color: COLORS.charcoal,
    marginBottom: SPACING.sm,
  },
  partDescription: {
    fontSize: 12,
    color: COLORS.stone,
    lineHeight: 18,
    marginBottom: SPACING.md,
  },
  featuresContainer: {
    gap: SPACING.xs,
  },
  featureBadge: {
    paddingHorizontal: SPACING.sm,
    paddingVertical: 4,
    borderRadius: 6,
  },
  featureText: {
    fontSize: 9,
    fontWeight: '500',
  },

  // Types Tab
  typesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: SPACING.md,
    justifyContent: 'center',
  },
  typeCard: {
    width: isSmallScreen ? '47%' : '31%',
    minWidth: isSmallScreen ? 150 : 140,
    maxWidth: 180,
    borderRadius: 18,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: COLORS.cloud,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 3,
    backgroundColor: COLORS.white,
  },
  typeCardHeader: {
    padding: SPACING.lg,
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.md,
  },
  typeIconContainer: {
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
  },
  typeName: {
    fontSize: 16,
    fontWeight: '800',
    marginBottom: 2,
  },
  typeSafety: {
    fontSize: 10,
    fontWeight: '600',
  },
  typeCardBody: {
    padding: SPACING.lg,
    paddingTop: 0,
  },
  typeDescription: {
    fontSize: 12,
    color: COLORS.stone,
    lineHeight: 18,
    marginBottom: SPACING.md,
  },
  examplesContainer: {
    marginBottom: SPACING.md,
  },
  examplesTitle: {
    fontSize: 11,
    fontWeight: '600',
    color: COLORS.charcoal,
    marginBottom: 6,
  },
  examplesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
  },
  exampleBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  exampleText: {
    fontSize: 9,
    fontWeight: '500',
  },

  // Safety Tab
  warningBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.md,
    backgroundColor: '#FEF2F2',
    padding: SPACING.lg,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: '#FCA5A5',
    marginBottom: SPACING.lg,
  },
  warningContent: {
    flex: 1,
  },
  warningTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: COLORS.danger,
    marginBottom: SPACING.xs,
  },
  warningText: {
    fontSize: 11,
    color: COLORS.danger,
    fontWeight: '500',
    lineHeight: 16,
  },
  safetyGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: SPACING.md,
    justifyContent: 'center',
    marginBottom: SPACING.lg,
  },
  safetyCard: {
    width: isSmallScreen ? '100%' : '48%',
    minWidth: isSmallScreen ? '100%' : 260,
    maxWidth: isSmallScreen ? '100%' : 380,
    backgroundColor: COLORS.white,
    padding: SPACING.lg,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: COLORS.cloud,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  safetyCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.md,
    marginBottom: SPACING.md,
  },
  ruleIconContainer: {
    width: 45,
    height: 45,
    borderRadius: 22.5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  ruleInfo: {
    flex: 1,
  },
  ruleName: {
    fontSize: 15,
    fontWeight: '700',
    color: COLORS.charcoal,
    marginBottom: SPACING.sm,
  },
  severityBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: SPACING.sm,
    paddingVertical: 4,
    borderRadius: 10,
    alignSelf: 'flex-start',
  },
  severityDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  severityText: {
    fontSize: 8,
    fontWeight: '700',
  },
  ruleDescription: {
    fontSize: 13,
    color: COLORS.stone,
    lineHeight: 20,
    marginBottom: SPACING.md,
  },
  tipsContainer: {
    backgroundColor: COLORS.sand,
    padding: SPACING.md,
    borderRadius: 12,
  },
  tipsTitle: {
    fontSize: 11,
    fontWeight: '600',
    color: COLORS.charcoal,
    marginBottom: 6,
  },
  tipItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
    marginBottom: 4,
  },
  tipDot: {
    width: 5,
    height: 5,
    borderRadius: 2.5,
  },
  tipText: {
    fontSize: 10,
    color: COLORS.stone,
    flex: 1,
    lineHeight: 15,
  },
  emergencyContainer: {
    backgroundColor: '#FEF3C7',
    padding: SPACING.lg,
    borderRadius: 18,
    borderWidth: 2,
    borderColor: '#FDE68A',
  },
  emergencyTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#92400E',
  },
  emergencySteps: {
    gap: SPACING.md,
  },
  emergencyStep: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.md,
    backgroundColor: COLORS.white,
    padding: SPACING.md,
    borderRadius: 12,
  },
  emergencyNumber: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#92400E',
    justifyContent: 'center',
    alignItems: 'center',
  },
  // ...removed duplicate stepNumberText...
  stepText: {
    fontSize: 13,
    color: '#92400E',
    fontWeight: '600',
    flex: 1,
  },

  // Features Section
  featuresSection: {
    paddingVertical: SPACING.xxl,
    paddingHorizontal: SPACING.md,
    backgroundColor: COLORS.white,
    position: 'relative',
  },
  featuresGrid: {
    flexDirection: isSmallScreen ? 'column' : 'row',
    gap: SPACING.lg,
    justifyContent: 'center',
    alignItems: isSmallScreen ? 'stretch' : 'flex-start',
  },
  featureCard: {
    flex: isSmallScreen ? 0 : 1,
    maxWidth: isSmallScreen ? '100%' : 300,
    backgroundColor: COLORS.sand,
    padding: SPACING.lg,
    borderRadius: 20,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 16,
    elevation: 3,
    borderWidth: 1,
    borderColor: COLORS.cloud,
  },
  iconWrapper: {
    width: 90,
    height: 90,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: SPACING.lg,
    position: 'relative',
  },
  iconGlow: {
    position: 'absolute',
    width: 90,
    height: 90,
    borderRadius: 45,
  },
  iconContainer: {
    width: 70,
    height: 70,
    borderRadius: 35,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.5)',
  },
  featureTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: COLORS.charcoal,
    marginBottom: SPACING.sm,
    textAlign: 'center',
  },
  featureDescription: {
    fontSize: 13,
    color: COLORS.stone,
    textAlign: 'center',
    lineHeight: 20,
  },

  // How It Works Section
  howItWorksSection: {
    paddingVertical: SPACING.xxl,
    paddingHorizontal: SPACING.md,
    backgroundColor: COLORS.sand,
  },
  stepsContainer: {
    flexDirection: isSmallScreen ? 'column' : 'row',
    gap: SPACING.lg,
    justifyContent: 'center',
    alignItems: isSmallScreen ? 'stretch' : 'flex-start',
  },
  stepCard: {
    flex: isSmallScreen ? 0 : 1,
    maxWidth: isSmallScreen ? '100%' : 280,
    backgroundColor: COLORS.white,
    padding: SPACING.lg,
    borderRadius: 20,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 4,
    borderWidth: 1,
    borderColor: COLORS.cloud,
  },
  stepMushroomContainer: {
    marginBottom: SPACING.lg,
  },
  stepContent: {
    alignItems: 'center',
    width: '100%',
  },
  stepNumberBadge: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: COLORS.forest,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: SPACING.md,
    shadowColor: COLORS.forest,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 2,
  },
  stepNumberText: {
    fontSize: 13,
    fontWeight: '800',
    color: COLORS.white,
  },
  stepIconContainer: {
    marginBottom: SPACING.sm,
  },
  stepTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: COLORS.charcoal,
    marginBottom: SPACING.sm,
    textAlign: 'center',
  },
  stepDescription: {
    fontSize: 13,
    color: COLORS.stone,
    lineHeight: 20,
    textAlign: 'center',
  },

  // CTA Section
  ctaSection: {
    paddingVertical: SPACING.xl,
    paddingHorizontal: SPACING.md,
    backgroundColor: COLORS.white,
  },
  ctaCard: {
    backgroundColor: COLORS.sage,
    borderRadius: 24,
    padding: SPACING.xxl,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 20,
    elevation: 6,
    position: 'relative',
    overflow: 'hidden',
  },
  ctaMushroomLeft: {
    position: 'absolute',
    bottom: 15,
    left: 15,
    opacity: 0.3,
  },
  ctaMushroomRight: {
    position: 'absolute',
    top: 15,
    right: 15,
    opacity: 0.3,
  },
  ctaContent: {
    alignItems: 'center',
  },
  ctaTitle: {
    fontSize: isSmallScreen ? 22 : 24,
    fontWeight: '800',
    color: COLORS.white,
    marginTop: SPACING.md,
    marginBottom: SPACING.md,
    textAlign: 'center',
  },
  ctaDescription: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.9)',
    textAlign: 'center',
    marginBottom: SPACING.lg,
    lineHeight: 22,
    maxWidth: 500,
  },
  ctaButton: {
    borderRadius: 22,
    overflow: 'hidden',
    marginBottom: SPACING.md,
    width: '100%',
    maxWidth: 280,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  ctaButtonInner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: SPACING.lg,
    paddingHorizontal: SPACING.lg,
    gap: SPACING.sm,
    backgroundColor: COLORS.white,
  },
  ctaButtonText: {
    fontSize: 15,
    fontWeight: '700',
    color: COLORS.forest,
  },
  ctaNote: {
    fontSize: 11,
    color: 'rgba(255, 255, 255, 0.8)',
    textAlign: 'center',
  },

  // Safety Section
  safetySection: {
    paddingVertical: SPACING.lg,
    paddingHorizontal: SPACING.md,
    backgroundColor: COLORS.sand,
  },
  // ...removed duplicate safetyCard...
  safetyContent: {
    flex: 1,
  },
  safetyTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#92400E',
    marginBottom: SPACING.sm,
  },
  safetyText: {
    fontSize: 12,
    color: '#92400E',
    lineHeight: 18,
  },

  // System Section
  systemSection: {
    paddingVertical: SPACING.lg,
    paddingHorizontal: SPACING.md,
    backgroundColor: COLORS.white,
  },
  systemCard: {
    backgroundColor: COLORS.sand,
    padding: SPACING.lg,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: COLORS.cloud,
  },
  systemHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: SPACING.md,
    flexWrap: 'wrap',
    gap: SPACING.sm,
  },
  systemTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
  },
  systemTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: COLORS.charcoal,
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingVertical: 4,
    paddingHorizontal: SPACING.md,
    borderRadius: 10,
    backgroundColor: `${COLORS.stone}15`,
  },
  statusConnected: {
    backgroundColor: `${COLORS.success}15`,
  },
  statusFailed: {
    backgroundColor: `${COLORS.danger}15`,
  },
  statusDot: {
    width: 7,
    height: 7,
    borderRadius: 3.5,
    backgroundColor: COLORS.stone,
  },
  dotConnected: {
    backgroundColor: COLORS.success,
  },
  dotFailed: {
    backgroundColor: COLORS.danger,
  },
  statusText: {
    fontSize: 10,
    fontWeight: '600',
    color: COLORS.stone,
  },
  systemMessage: {
    fontSize: 12,
    color: COLORS.stone,
    marginBottom: SPACING.md,
    lineHeight: 18,
  },
  testButton: {
    backgroundColor: COLORS.forest,
    paddingVertical: SPACING.md,
    borderRadius: 12,
    alignItems: 'center',
  },
  testButtonText: {
    color: COLORS.white,
    fontSize: 13,
    fontWeight: '600',
  },

  // Footer
  footer: {
    backgroundColor: COLORS.charcoal,
    paddingVertical: SPACING.xl,
    paddingHorizontal: SPACING.md,
  },
  footerContent: {
    alignItems: 'center',
  },
  footerBrand: {
    alignItems: 'center',
    marginBottom: SPACING.md,
  },
  footerTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: COLORS.white,
    marginTop: SPACING.sm,
    marginBottom: 2,
  },
  footerTagline: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.7)',
  },

  // Mushroom Resources Carousel - Enhanced Design
  carouselContainer: {
    marginVertical: SPACING.xl,
    paddingHorizontal: SPACING.md,
  },
  carouselHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: SPACING.lg,
    backgroundColor: COLORS.white,
    padding: SPACING.md,
    borderRadius: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  carouselArrow: {
    padding: SPACING.sm,
    borderRadius: 12,
    backgroundColor: `${COLORS.sage}15`,
    borderWidth: 1,
    borderColor: COLORS.sage,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 1,
  },
  carouselTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: COLORS.forest,
    textAlign: 'center',
    flex: 1,
  },
  carouselCardsContainer: {
    flexDirection: 'row',
  alignItems: 'flex-start',
  paddingHorizontal: SPACING.lg,
  gap: SPACING.xl, // Larger gap between cards
},
  carouselScrollView: {
    flexGrow: 0,
  },
  urlCard: {
   backgroundColor: COLORS.white,
  borderRadius: 16, // Slightly smaller radius
  padding: SPACING.lg,
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 4 }, // Lighter shadow
  shadowOpacity: 0.08, // More subtle shadow
  shadowRadius: 8,
  elevation: 4,
  width: 280, // Smaller, more manageable width
  marginRight: 0, // Remove margin since gap handles spacing
  borderWidth: 1,
  borderColor: COLORS.cloud,
},
  urlCardHeader: {
     flexDirection: 'row',
  alignItems: 'center',
  marginBottom: SPACING.md,
},
  urlCardTitle: {
    fontSize: 18, // Slightly smaller
  fontWeight: '700',
  color: COLORS.charcoal,
  flex: 1,
  marginLeft: SPACING.sm,
},
  urlCardDescription: {
    fontSize: 14,
  color: COLORS.stone,
  marginBottom: SPACING.lg,
  lineHeight: 20,
},
  urlCardButton: {
     backgroundColor: COLORS.forest,
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'center',
  paddingVertical: SPACING.sm,
  paddingHorizontal: SPACING.lg,
  borderRadius: 8, // Smaller radius
  marginTop: SPACING.sm,
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 2 },
  shadowOpacity: 0.15,
  shadowRadius: 4,
  elevation: 2,
},
  urlCardButtonText: {
    color: COLORS.white,
    fontSize: 15,
    fontWeight: '600',
  },
  carouselIndicators: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: SPACING.md,
    gap: SPACING.sm,
  },
  carouselIndicator: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: COLORS.cloud,
  },
  activeCarouselIndicator: {
    backgroundColor: COLORS.forest,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
  },
});